binutils_version: '2.44'
c_compiler: gcc
c_stdlib: sysroot
c_stdlib_version: '2.28'
channel_sources: conda-forge/label/sysroot-with-crypt,conda-forge
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: linux-64
cross_target_stdlib: sysroot
cross_target_stdlib_version: '2.28'
cxx_compiler: gxx
extend_keys:
- extend_keys
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
fortran_compiler: gfortran
gcc_maj_ver: '15'
gcc_version: 15.2.0
ignore_build_only_deps:
- python
- numpy
libgfortran_soname: '5'
libgomp_ver: 1.0.0
lua: '5'
numpy: '1.26'
openmp_ver: '4.5'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: linux-64
python: '3.12'
r_base: '3.5'
target_platform: linux-64
triplet: x86_64-conda-linux-gnu
with_conda_specs: 'true'
