triplet:
  - x86_64-conda-linux-gnu      # [linux and x86_64]
  - powerpc64le-conda-linux-gnu # [ppc64le]
  - aarch64-conda-linux-gnu     # [linux and aarch64]
  - x86_64-w64-mingw32          # [win]
gcc_version:
  - 15.2.0                      # [not ANACONDA_ROCKET_ENABLE_GCC13 and not ANACONDA_ROCKET_ENABLE_GCC14]
  - 14.3.0                      # [ANACONDA_ROCKET_ENABLE_GCC14]
  - 13.4.0                      # [ANACONDA_ROCKET_ENABLE_GCC13]
gcc_maj_ver:
  - 15                          # [not ANACONDA_ROCKET_ENABLE_GCC13 and not ANACONDA_ROCKET_ENABLE_GCC14]
  - 14                          # [ANACONDA_ROCKET_ENABLE_GCC14]
  - 13                          # [ANACONDA_ROCKET_ENABLE_GCC13]
libgfortran_soname:
  - 5                           # [not ANACONDA_ROCKET_ENABLE_GCC13 and not ANACONDA_ROCKET_ENABLE_GCC14]
  - 5                           # [ANACONDA_ROCKET_ENABLE_GCC14]
  - 5                           # [ANACONDA_ROCKET_ENABLE_GCC13]
binutils_version:
  - 2.44
cross_target_platform:
  - linux-64                    # [linux and x86_64]
  - linux-ppc64le               # [ppc64le]
  - linux-aarch64               # [linux and aarch64]
  - win-64                      # [win]
cross_target_stdlib_version:
  - 2.28                        # [linux and x86_64]
  - 2.28                        # [ppc64le]
  - 2.28                        # [linux and aarch64]
  - 12                          # [win]
cross_target_stdlib:
  - sysroot                     # [linux and x86_64]
  - sysroot                     # [ppc64le]
  - sysroot                     # [linux and aarch64]
  - m2w64-sysroot               # [win]
# openmp versions
openmp_ver:
  - 4.5
libgomp_ver:
  - 1.0.0
channel_sources:
  - conda-forge/label/sysroot-with-crypt,conda-forge
# we could use stdlib("m2w64_c"), but this allows uniform use in setup_compiler.sh
c_stdlib:                       # [win]
  - m2w64-sysroot               # [win]
c_stdlib_version:               # [win]
  - 12                          # [win]
with_conda_specs:
  - true
  - false
